version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      eslint:
        patterns:
          - "*eslint*"
      hpke-js:
        patterns:
          - "hpke-js"
          - "@hpke/*"
      typedoc:
        patterns:
          - "typedoc"
          - "typedoc-*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
