name: docs

on:
  push:
    branches:
      - main
jobs:
  docs:
    name: build typedocs and put them on github pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - run: npm ci
    - run: npm run build
    - run: npm run docs
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@v4.6.3
      with:
        branch: gh-pages
        folder: docs
